const ADD_TWEET = 'ADD_TWEET'
const FETCH_TWEETS = 'FETCH_TWEETS'
const FETCH_IN_PROGRESS = 'FETCH_IN_PROGRESS'
const FETCH_SUCCESS = 'FETCH_SUCCESS'

export default {
  ADD_TWEET,
  FETCH_TWEETS,
  FETCH_IN_PROGRESS,
  FETCH_SUCCESS,
}
