const ADD_TWEET = 'ADD_TWEET'
const ADD_TWEET_IN_PROGRESS = 'ADD_TWEET_IN_PROGRESS'
const ADD_TWEET_SUCCESS = 'ADD_TWEET_SUCCESS'
const ADD_TWEET_FAIL = 'ADD_TWEET_FAIL'
const FETCH_TWEETS = 'FETCH_TWEETS'
const FETCH_TWEETS_IN_PROGRESS = 'FETCH_TWEETS_IN_PROGRESS'
const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS'
const FETCH_PROFILE = 'FETCH_PROFILE'
const FETCH_PROFILE_IN_PROGRESS = 'FETCH_PROFILE_IN_PROGRESS'
const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
const LOGIN = 'LOGIN'
const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAIL = 'LOGIN_FAIL'
const LOGOUT = 'LOGOUT'
const SIGNUP = 'SIGNUP'
const SIGNUP_IN_PROGRESS = 'SIGNUP_IN_PROGRESS'
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
const SIGNUP_FAIL = 'SIGNUP_FAIL'

export default {
  ADD_TWEET,
  ADD_TWEET_IN_PROGRESS,
  ADD_TWEET_SUCCESS,
  ADD_TWEET_FAIL,
  FETCH_TWEETS,
  FETCH_TWEETS_IN_PROGRESS,
  FETCH_TWEETS_SUCCESS,
  FETCH_PROFILE,
  FETCH_PROFILE_IN_PROGRESS,
  FETCH_PROFILE_SUCCESS,
  LOGIN,
  LOGIN_IN_PROGRESS,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  LOGOUT,
  SIGNUP,
  SIGNUP_IN_PROGRESS,
  SIGNUP_SUCCESS,
  SIGNUP_FAIL,
}
