const ADD_TWEET = 'ADD_TWEET'
const FETCH_TWEETS = 'FETCH_TWEETS'
const FETCH_TWEETS_IN_PROGRESS = 'FETCH_TWEETS_IN_PROGRESS'
const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS'
const FETCH_PROFILE = 'FETCH_PROFILE'
const FETCH_PROFILE_IN_PROGRESS = 'FETCH_PROFILE_IN_PROGRESS'
const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
const LOGIN = 'LOGIN'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAIL = 'LOGIN_FAIL'
const LOGOUT = 'LOGOUT'

export default {
  ADD_TWEET,
  FETCH_TWEETS,
  FETCH_TWEETS_IN_PROGRESS,
  FETCH_TWEETS_SUCCESS,
  FETCH_PROFILE,
  FETCH_PROFILE_IN_PROGRESS,
  FETCH_PROFILE_SUCCESS,
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  LOGOUT,
}
